# Generated by Django 2.1.5 on 2019-02-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Technologyname', models.CharField(max_length=255)),
                ('Opening', models.IntegerField()),
            ],
        ),
    ]
